source 'https://github.com/CocoaPods/Specs.git'

target 'TTProgressButton', :exclusive => true do
  pod "TTProgressButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "TTProgressButton", :path => "../"

  
end
